name: lexininos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: any
  path: any
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.9
  auto_size_text: ^3.0.0
  clipboard: ^0.1.3
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo.png
    - assets/msg.png
    - assets/ajuste.png
    - assets/UBR1.jpg
    - assets/UBR2.jpg
    - assets/UBR3.jpg
    - assets/confi.png
    - assets/señal.png
    - assets/background.jpg
    - assets/niño.png
    - assets/fonts/Cocogoose-Pro-Bold-trial.ttf
    #iconos de las pruebas
    - assets/sopa.png
    - assets/palabras.jpg
    - assets/rima.jpg
    - assets/figuras.jpg
    #iconos de test2
    - assets/animales.jpg
    - assets/objetos.jpg
    - assets/frutas.jpg
    #conecta y aprende
    #animales
    - assets/animales/buho.jpg
    - assets/animales/canguro.jpg
    - assets/animales/cebra.jpg
    - assets/animales/delfin.jpg
    - assets/animales/elefante.jpg
    - assets/animales/jirafa.jpg
    - assets/animales/leon.jpg
    - assets/animales/mono.jpg
    - assets/animales/panda.jpg
    - assets/animales/tigre.jpg
    #frutas
    - assets/frutas/cereza.jpg
    - assets/frutas/fresa.jpg
    - assets/frutas/kiwi.jpg
    - assets/frutas/limon.jpg
    - assets/frutas/mango.jpg
    - assets/frutas/manzana.jpg
    - assets/frutas/naranja.jpg
    - assets/frutas/platano.jpg
    - assets/frutas/sandia.jpg
    - assets/frutas/uva.jpg
    #objetos
    - assets/objetos/bolsa.jpg
    - assets/objetos/gafas.jpg
    - assets/objetos/gorra.jpg
    - assets/objetos/lapiz.jpg
    - assets/objetos/libro.jpg
    - assets/objetos/mesa.jpg
    - assets/objetos/pelota.jpg
    - assets/objetos/reloj.jpg
    - assets/objetos/silla.jpg
    - assets/objetos/zapato.jpg
    #test4
    - assets/test4/test1.png
    - assets/test4/opcion1.png
    - assets/test4/opcion3.png
    - assets/test4/opcion4.png
    - assets/test4/correcta.png
    - assets/test4/test1.png
    
    - assets/test4/op1.png
    - assets/test4/op2.png
    - assets/test4/op3.png
    - assets/test4/correcto1.png
    - assets/test4/test2.png

    - assets/test4/opc1.png
    - assets/test4/opc2.png
    - assets/test4/opc3.png
    - assets/test4/correcto2.png
    - assets/test4/test3.png

    - assets/test4/opci1.png
    - assets/test4/opci2.png
    - assets/test4/opci3.png
    - assets/test4/correcto3.png
    - assets/test4/test4.png

    - assets/test4/opcio1.png
    - assets/test4/opcio2.png
    - assets/test4/opcio3.png
    - assets/test4/correcto4.png
    - assets/test4/test5.png
    #avares
    - assets/avatares/avatar1.png
    - assets/avatares/avatar2.png
    - assets/avatares/avatar3.png
    - assets/avatares/avatar4.png

  fonts:
    - family: Cocogoose
      fonts:
        - asset: assets/fonts/Cocogoose-Pro-Bold-trial.ttf
